```{r results='hide'}

rootRSourse <- 'LASPUMSS/APLICACION-DE-LA-METODOLOGIA-CAMEL-BOLIVIA/R'
sapply( list.files(rootRSourse, full.names=TRUE, pattern='\\.[rR]$'), source )

require(dplyr)
require(stringr)
require(glue)
require(ggplot2)
require(patchwork)
require(knitr)
require(kableExtra)
require(huxtable)

# VARIABLES GLOBALES DEL CAPITULO
datBasic <- getDatEEFF()
dat <- getDatEEFFNormalizada(by='TIPO_DE_ENTIDAD')
datGroupBySector <- getDatEEFFByGroup(datBasic,by = 'TIPO_DE_ENTIDAD' )
```

El presente diagnóstico de solidez financiera del sistema financiero de Bolivia tiene como fuente de datos los estados financieros resumidos publicados por la Autoridad del sistema financiero [@ASFI-DATOS], que posteriormente fueron agrupados por sectores financieros.

El número de observaciones de los datos manejados por esta investigación alcanzan a `r nrow(datBasic)`, donde cada observación corresponde a un balance general y un estado de resultados en un punto del tiempo entre las fechas (`r min(datBasic$FECHA)` - `r max(datBasic$FECHA)`) con una frecuencia mensual, dichos estados financieros se clasifican o agrupan por sectores financieros los cuales son:

- Bancos múltiples
- Bancos PYME.
- Bancos de desarrollo productivo.
- Instituciones financieras de desarrollo.
- Entidades financieras de vivienda.
- Cooperativas.

Una vez agrupados los datos por sectores resultan en un total de `r nrow(datGroupBySector)` observaciones, donde el agrupamiento debe entenderse como la suma total de una cuenta correspondiente a un sector financiero. 

Así también, los indicadores son procesados o calculados por medio de funciones desarrolladas por el investigador en el lenguaje de programación R, con excepción del coeficiente de adecuación patrimonial (Ver sección \@ref(mtIndicadoresFinancierosCapCap)), que fueron obtenidos ya procesados de la misma fuente de los estados financieros [@ASFI-DATOS]. 
